Vagrant.configure(2) do |config|
	config.vm.box = "envimation/ubuntu-xenial-docker"
	
	config.vm.provider "virtualbox" do |v|
		v.memory = 5000
		v.cpus = 2
	end
	
	config.vm.network "private_network", ip: "192.168.50.99"
		
end
